name: Flutter Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest  # Use macOS for iOS simulator access
    strategy:
      matrix:
        device: [android, ios, chrome]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - name: Run tests on ${{ matrix.device }}
      run: flutter test -d ${{ matrix.device }}